name: Test Builder CI

on:
  push:
    branches:
      - main
    paths:
      - "**/Dockerfile"
      - "root/**"

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Enviroment Variables
        id: variables
        env:
          DOCKERHUB_IMAGE: vcxpz/lidarr
          DOCKERIMAGE_TAG: testing
          LIDARR_BRANCH: nightly
        run: |
          echo "::set-output name=DOCKERHUB_IMAGE::$DOCKERHUB_IMAGE"
          echo "::set-output name=DOCKERIMAGE_TAG::$DOCKERIMAGE_TAG"
          echo "::set-output name=LIDARR_RELEASE::$(curl -sL "https://lidarr.servarr.com/v1/update/${LIDARR_BRANCH}/changes?os=linuxmusl" | jq -r '.[0].version')"
          echo "::set-output name=LIDARR_BRANCH::$LIDARR_BRANCH"

      - name: Docker Login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u vcxpz --password-stdin

      - name: Build The Docker Image
        env:
          DOCKERHUB_IMAGE: ${{ steps.variables.outputs.DOCKERHUB_IMAGE }}
          LIDARR_RELEASE: ${{ steps.variables.outputs.LIDARR_RELEASE }}
          LIDARR_BRANCH: ${{ steps.variables.outputs.LIDARR_BRANCH }}
        run: |
          docker build --no-cache --pull . --file Dockerfile --build-arg LIDARR_BRANCH="$LIDARR_BRANCH" --build-arg LIDARR_RELEASE="$LIDARR_RELEASE" --build-arg BUILD_DATE="$(date +%Y-%m-%d)" --tag "$DOCKERHUB_IMAGE":cibuild

      - name: Tag And Push Docker Image
        env:
          DOCKERHUB_IMAGE: ${{ steps.variables.outputs.DOCKERHUB_IMAGE }}
          DOCKERIMAGE_TAG: ${{ steps.variables.outputs.DOCKERIMAGE_TAG }}
        run: |
          docker tag "$DOCKERHUB_IMAGE":cibuild "$DOCKERHUB_IMAGE":"$DOCKERIMAGE_TAG"
          docker push "$DOCKERHUB_IMAGE":"$DOCKERIMAGE_TAG"
